#!/bin/sh

set -e

REF="$1"
OLDREV="$2"
NEWREV="$3"

cd /etc/puppet

git --git-dir /etc/puppet/repo archive --format=tar "$NEWREV" | sudo tar xf -

sudo librarian-puppet install

sudo puppet apply --show_diff <%= @future_parser ? "--parser=future " : "" %>./nodes

# Apply puppet to all containers on the node, too
if [ -d /srv/lxc ]; then
	for d in /srv/lxc/*; do
		if [ -f "$d/config" ]; then
			sudo lxc-attach -n $(basename $d) -- puppet apply --show_diff <%= @future_parser ? "--parser=future " : "" %>/etc/puppet/nodes
		fi
	done
fi
